module WriteBack where

import Types

-- Generated by execution step of pipeline.
-- FInstruction to machine of values to update.
data WriteBack
    = WriteReg PhyReg Val
    | WriteMem Addr Val
    | WritePrint String
    | NoOp
    | Terminate
    deriving (Show, Eq)
