module WriteBack where

import Types

type Valid = Bool

-- Generated by execution step of pipeline.
-- FInstruction to machine of values to update.
data WriteBack
    -- Valid used to determine whether to flush the pipeline if a load is
    -- determined to be invalid.
    = WriteReg PhyReg Val Valid
    | WriteMem Addr Val
    | WritePrint String
    | NoOp
    | Terminate
    deriving (Show, Eq)
