module WriteBack where

import Instr (RegIdx, Val, Addr)

-- Generated by execution step of pipeline.
-- Instruction to machine of values to update.
data WriteBack
    = WriteReg RegIdx Val
    | WriteMem Addr Val
    | WritePrint String
    | NoOp
    | Terminate
    deriving (Show)
